#!/bin/sh

set -eu

make_image() {
	echo "[+] Getting appimagetool..."
	get_appimagetool
	echo "[+] Getting dockie..."
	get_dockie
	echo "[+] Getting proot..."
	get_proot
	echo "[+] Building AppDir..."
	mkdir -p AppDir/usr/bin
	mkdir -p AppDir/usr/lib/dockie
	cp AppRun AppDir/
	cp dockie.desktop AppDir/
	cp dockie.png AppDir/
	cp dockie AppDir/usr/bin
	cp proot AppDir/usr/bin
	cp docker-hub-pull AppDir/usr/lib/dockie
	echo "[+] Building AppImage..."
	ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir >/dev/null
	echo "[+] All done!"
	echo
	echo "You can now use Dockie with ./dockie-x86_64.AppImage or copy it somewhere in your PATH"
	echo
}

get_proot() {
	curl -sL https://gitlab.com/proot/proot/-/jobs/537307719/artifacts/download >artifacts.zip
	unzip -o artifacts.zip
	cp dist/proot .
}

get_appimagetool() {
	curl -sL https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage >appimagetool-x86_64.AppImage
	chmod +x appimagetool-x86_64.AppImage
}

get_dockie() {
	rm -rf dockie-repo
	git clone -q --depth 1 https://github.com/cristianrz/dockie.git dockie-repo
	cp dockie-repo/docs/whale_small.png dockie.png
	cd dockie-repo
	sh configure
	make
	cd ..
	cp dockie-repo/dockie .
	chmod +x dockie
	cp dockie-repo/contrib/docker-hub-pull .
}

clean() {
	rm -f dockie
	rm -f dockie.AppImage
	rm -f appimagetool-x86_64.AppImage
	rm -f dockie.png
	rm -f dockie-x86_64.AppImage
	rm -f docker-hub-pull
	rm -rf AppDir
	rm -rf artifacts.zip
	rm -rf dist
	rm -rf dockie-repo
	rm -rf proot
}

case "${1-}" in
clean) clean ;;
"") make_image ;;
*) echo 'unregnised argument' >&2 && exit 1 ;;
esac
